# Generated by Django 3.0.3 on 2020-04-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0002_beverage_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='coinId',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='coinId',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='paymentId',
        ),
        migrations.AddField(
            model_name='transaction',
            name='coin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Coin',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
