# Generated by Django 3.0.3 on 2020-04-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0004_change'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Change',
            new_name='Coin',
        ),
    ]
